---
# tasks file for rsyslog

# Install and configure rsyslog
- name: Make sure rsyslog and logrotate are installed
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items: 
    - rsyslog
    - logrotate
  tags: rsyslogd

- name: Send log messages from cron to /var/log/cron.log
  template: src=cron.conf.j2 dest=/etc/rsyslog.d/cron.conf owner=root group=root backup=no
  notify: Restart rsyslogd
  tags: rsyslogd

- name: Make sure rsyslog is running and enabled
  service: name=rsyslog state=running enabled=yes
  tags: rsyslogd

