---
# Provision AWS instances
# Based heavily on the Ansible guide and documentation on AWS / EC2:
# http://docs.ansible.com/guide_aws.html
# http://docs.ansible.com/ec2_module.html


# Provision the EC2 instanses using Ansible ec2 module
- name: Provision EC2 instances
  hosts: local
  sudo: no
  connection: local
  gather_facts: False

  tasks:
    # Get encrypted EC2 key(s) from Ansible vault
    - name: Install EC2 deploy user private key
      shell: echo "{{ ec2_deploy_key }}" > {{ ec2_deploy_key_file }}  && chmod 600 {{ ec2_deploy_key_file }}

    - name: Add SSH key to ansible user with ssh-add
      shell: ssh-add {{ ec2_deploy_key_file }}

    - name: Launch "Minecraft" instances
      ec2: 
        instance_type: t2.micro
        image: ami-b83c0aa5
        region: eu-central-1
        group: default
        monitoring: yes
        wait: yes
        key_name: crosskey_ec2_deploy
        count: 8 
        instance_tags:
          Name: Minecraft
      register: ec2

    - name: Launch "Webserver" instances
      ec2: 
        instance_type: t2.micro
        image: ami-b83c0aa5
        region: eu-central-1
        group: default
        monitoring: yes
        wait: yes
        key_name: crosskey_ec2_deploy
        count: 2 
        instance_tags:
          Name: Webserver
      register: ec2


    - name: Add instances public IPs to Ansible inventory(in-memory)
      add_host: 
        hostname={{ item.public_ip }} 
        groupname=minecraft-instances
        ansible_ssh_private_key_file={{ ec2_deploy_key_file }}
      with_items: ec2.instances

    - name: Add instances and SSH keys to local Ansible inventory
      local_action: lineinfile dest=inventory/minecraft_servers regexp="{{ item.public_dns_name }}" insertafter="# EC2 Instances" line="{{ item.public_dns_name }} ansible_ssh_private_key_file={{ ec2_deploy_key_file }}"
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=300 state=started
      with_items: ec2.instances

