---
galaxy_info:
  author: Kim Halavakoski
  description: Postgres role
  company: Deductive Labs Ab Ltd.
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.8
  platforms:
    - name: Ubuntu
      versions:
        - all
    
  categories:
  - database
  - database:sql

dependencies: []

