---
galaxy_info:
  author: benwebber
  description:
  license: Apache 2.0
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
  categories:
  - system
dependencies: []
