# tasks file for postfix
---

- name: ensure postfix is installed
  apt:  pkg=postfix state=installed
  tags: 
    - postfix
    - install

- name: create postfix configuration
  template: src=etc/postfix/{{item}}.j2 dest={{postfix_conf_dir}}/{{item}} mode=0644 owner=root group=root
  notify: restart postfix
  with_items:
    - main.cf
    - master.cf
  tags:
    - postifx
    - config

- name: create tls_policy configuration
  template: src=etc/postfix/tls_policy.j2 dest={{postfix_conf_dir}}/tls_policy mode=0600 owner=root group=root
  notify: reload postfix
  register: postfix_tls_policy_result
  when: postfix_tls_policy.0 is defined
  tags:
    - postfix
    - config

- name: ensure tls_policy is compiled
  shell: postmap {{postfix_conf_dir}}/tls_policy
  notify: reload postfix
  when: postfix_tls_policy_result | changed
  tags:
    - configuration
    - postfix

- name: ensure postfix is running
  service: name=postfix state=running enabled=yes
  tags:
    - postfix
    - service
