- name: generate {{ list }} data
  sudo: false
  local_action: script generate_minecraft_acl.py -l {{ list }} {{ data | join(' ') }}
  register: acl

- name: update {{ list }}
  template:
    src=acl.json.j2
    dest={{ minecraft_home }}/{{ list }}.json
    owner={{ minecraft_user }}
    group={{ minecraft_group }}
    mode=0644
  notify:
    - restart Minecraft
