# requires --extra-vars="target=hostspec"

- name: reboot hosts
  hosts: "{{ target }}"
  gather_facts: False
  user: root
  serial: 1

  tasks:
  - name: Reboot host
    command: /sbin/shutdown -r 1

  - name: Wait for host to come back - up to 15 minutes
    local_action: wait_for host={{ target }} port=22 delay=120 timeout=900 search_regex=OpenSSH

  - name: Sync host time with ntpdate
    command: ntpdate -u ntp.leaseweb.com
