---
# Terminate AWS instances

- hosts: all
  gather_facts: True
  user: ubuntu
  sudo: True
  tasks:

    # fetch instance data from the metadata servers in ec2
    - ec2_facts:

    # just show the instance-id
    - debug: msg= "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"

- hosts: all
  gather_facts: True
  connection: local
  vars:
    region: "eu-central-1"
  tasks:
    - name: Terminate all instances
      ec2: state='absent'
           region={{ region }}
           instance_ids={{ item }}
           wait=true
      with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']
