# tasks file for nginx
---

- name: Install nginx
  apt: pkg=nginx state=latest update_cache=true
  notify:
    - Start nginx
  tags: 
    - nginx


- name: Disabled the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Restart nginx
  tags: 
    - nginx


- name: Allow http(tcp/80) through ufw
  ufw: rule=allow port=80 proto=tcp
  tags: 
    - nginx


- name: Allow https(tcp/443) through ufw
  ufw: rule=allow port=443 proto=tcp
  tags: 
    - nginx


- name: Make sure nginx is running and enabled to start at boot           
  service: name=nginx state=running enabled=yes                           
  tags:                                                                        
    - nginx
